package com.myspace.test_git;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TestModel() {
    }




}